// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujaqobscoxltlkdfxhkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqYXFvYnNjb3hsdGxrZGZ4aGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzczMTIsImV4cCI6MjA1OTIxMzMxMn0.o-HThOdYqqexTD-nMPCUgXH086EDaRURZmt7w2pFzoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);